apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-prediction
  labels:
    app: flight-price-prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-price-prediction
  template:
    metadata:
      labels:
        app: flight-price-prediction
    spec:
      containers:
        - name: flight-price-prediction
          image: aparnapraturi/flight_price_prediction:latest
          ports:
            - containerPort: 5000
