apiVersion: v1
kind: Service
metadata:
  name: flight-price-prediction-service
spec:
  selector:
    app: flight-price-prediction
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 5000  
  type: LoadBalancer 
