apiVersion: v1
kind: Service
metadata:
  name: flight-price-prediction-service
spec:
  selector:
    app: flight-price-prediction
  ports:
    - protocol: TCP
      port: 80         # External port (accessible from outside the cluster)
      targetPort: 5000  # Internal container port (where the app is listening)
  type: LoadBalancer  # Expose service externally (use ClusterIP for internal only)
